API_KEY = "YOUR_TWELVEDATA_API_KEY"
TELEGRAM_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN"
TELEGRAM_CHAT_ID = "YOUR_CHAT_ID"
SYMBOLS = ["EUR/USD", "XAU/USD", "GBP/USD", "USD/JPY"]
TIMEFRAMES = ["15min", "1h", "4h"]